spring:
  application:
    name: itoken-zuul
  zipkin:
    base-url: http://172.17.11.220:9411

server:
  port: 8769

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.11.220:8761/eureka/

zuul:
  routes:
    api-admin:
      path: /api/admin/**
      serviceId: itoken-admin-service

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
