spring:
  application:
    name: itoken-zipkin

server:
  port: 9411

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.11.220:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

