spring:
  application:
    name: itoken-eureka
  zipkin:
    base-url: http://172.17.11.220:9411

server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    # 将自己注册到 Eureka 构建集群环境
    registerWithEureka: true
    # 表示是否要从其他 Eureka 获取信息
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.17.11.220:8761/eureka/,http://172.17.11.220:8861/eureka/,http://172.17.11.220:8961/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"