spring:
  application:
    name: itoken-admin
  zipkin:
    base-url: http://172.17.11.220:9411

server:
  port: 8084

eureka:
  client:
    serviceUrl:
      defaultZone: http://172.17.11.220:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

