spring:
  application:
    name: itoken-eureka
  zipkin:
    base-url: http://itoken-zipkin:9411

server:
  port: 8761

eureka:
  client:
    # 将自己注册到 Eureka 构建集群环境
    registerWithEureka: false
    # 表示是否要从其他 Eureka 获取信息
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"