spring:
  application:
    name: itoken-config
  zipkin:
    base-url: http://itoken-zipkin:9411
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/draperstudio/itoken-config
          search-paths: /respo

server:
  port: 8888

eureka:
  client:
    serviceUrl:
      defaultZone: http://itoken-eureka:8761/eureka/

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"

